### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by qurge** [oiuv/phpems#33]
Warning: Invalid argument supplied for foreach() in C:\\phpems\data\compile\exam\tpls\app\%%cpl%%index.php on line 13

**Comment by oiuv** [comment]
正式项目可以先关闭警告，或者自己修复一下PR上来，主要是没有判断是否是数组造成的。

**Comment by qurge** [comment]
> 正式项目可以先关闭警告，或者自己修复一下PR上来，主要是没有判断是否是数组造成的。

是的，我关闭调试模式就好了，自己摸索出来了
